snowflake_dbt_myproject:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "ma04582.eu_central_2.aws"    
      user: "Fatma"
      password: "Ff@1234567890123"
      role: "ACCOUNTADMIN"
      database: "finance_db"
      warehouse: "finance_wh"
      schema: "raw"
      threads: 4
      client_session_keep_alive: False
